### ISSUE TITLE
Crypt Keeper Villager Art Design

### ISSUE THREAD

**Issue by pyromaniac3** [GDACollab/Malisense#103]

**Comment by Carmencing** [comment]
![Image](https://github.com/GDACollab/Malisense/assets/116137283/2ac87d7b-24c7-4902-8947-6f3465174dd9)

**Comment by Carmencing** [comment]
https://drive.google.com/drive/folders/1F_ZFlNgF6On0uQm021v-uF1WDrQfpqRE?usp=sharing
