### ISSUE TITLE
(Sprint 3) Item Hotbar

### ISSUE THREAD

**Issue by mli254** [GDACollab/Malisense#136]
- Design template UI

Build a system to display the JoshPlayer inventory currently on the player controller. Use template art assets. Cross collaborate with Josh to add items to the main scene.

**Comment by SlimeCubed** [comment]
Zachary Messer - @slime_cubed
I'll make a thread for this task

**Comment by umjunsik2002** [comment]
If anyone interested in joining this task, please access to "(S3) 3 Items + Hotbar" thread since most of us do not have teammates and going to work in the same task!
