### ISSUE TITLE
Menu Ui Art

### ISSUE THREAD

**Issue by pyromaniac3** [GDACollab/Malisense#209]
## YOUR TASK
you will be making UI buttons for:
* the START button
> > this will also be CONTINUE if there is a save
* the NEW GAME button
* the OPTIONS button
* the CREDITS button
* the QUIT button

all of these will be for the title screen of Malisense.

## IMPORTANT INFO
be sure to look at the Malisense style guide and pitch to get a feel for the style of the UI!

when finished, PLEASE post your work both here and in the [google drive](https://drive.google.com/drive/u/1/folders/1gtiB1lhKfEXAWdxSHlQhxOD-SS_ohg8W)
remember the naming conventions, FirstLast_WhatYouWorkedOn (EX HarryPotter_SightBeastConcept)

## DEADLINE
deadline

## RESOURCES
[style guide](https://drive.google.com/drive/u/1/folders/1QWI8rraJAitwnRSk73TRQL9EuQ_TyUuo)
[masterdoc](https://docs.google.com/document/d/1M3hUuHexWxV5WJNgNRJL2LLwy9FOPtMyLTJvGn7mA6o/edit)
[aesthetics doc](https://docs.google.com/document/d/1mbgC0dvMyfjZSyWe5TRBYXbnDRmp9-xCF7DLbAZtAEo/edit#heading=h.7pull51vl4yr)

**Comment by Carmencing** [comment]
https://drive.google.com/drive/folders/1LhtWaVyXlMGOOEO4pfU91NAIVrhZCeH5?usp=sharing
