### ISSUE TITLE
Sound Reference Tracks Doc

### ISSUE THREAD

**Issue by vinhta1** [GDACollab/Malisense#33]
**Soft Deadline: End of Sprint 1; living document**
Make a document for music and SFX references for Malisense!
Example documents from previous years:
[Asterion's Reference Track Document](https://docs.google.com/document/d/1ZAwIfjNAF5_gGOLUjyIyHn4oyVqrF7TlzpEMxbJKIps/edit#heading=h.lr9fxf1w92mh)
[TacoCat's Reference Track Document](https://docs.google.com/document/d/1JSjzH8wE4IJRplg6qd8-3ro91DqOIPjnKJWpBGAB2j0/edit?usp=sharing)

To get started, being adding to the following placeholder document!
https://docs.google.com/document/d/1Xn94S6134CF94ffh6uQjNtoSpftv68LhzL9c53_J-ec/edit

If you are working on this task, please comment down below your name and Discord.

**Comment by Starendi** [comment]
Name: Ulises Gonzalez
Disc: Ulises "Starendi" G.
