### ISSUE TITLE
Writing: Player Character concepting

### ISSUE THREAD

**Issue by celine218** [GDACollab/Malisense#38]
**2-3 people for this task!** 

What is this character's name? Pronouns? 
What are their motivations?
What is their backstory? 
Any additional information is welcomed! 

**Work with art to help with the visual design**

**Comment by serengirlaxy** [comment]
Here is the current document for it!
https://docs.google.com/document/d/1PcZz_m90ocvcFoF8Gc0uIwMlpoZDRA9g3wOT6m2b7qo/edit?usp=sharing
