### ISSUE TITLE
Writing: NPC 4: High Priest/Clergy concept:

### ISSUE THREAD

**Issue by celine218** [GDACollab/Malisense#49]
**1 person** 

General motivations 
Work in style guide to take note of the way they act 
Check-in with design

**Comment by ivydudzik** [comment]
Ivy Dudzik - naiaelysia on Discord

**Comment by ivydudzik** [comment]
Concept Doc: 

https://docs.google.com/document/d/1VhxHGhRkEyHaXD6v-u22F_GC7__3LRhMUpptmAc88Sc/edit
