### ISSUE TITLE
Writing: (ROUGH DRAFTS) Dungeon Notes: Pre-Convergence 

### ISSUE THREAD

**Issue by serengirlaxy** [GDACollab/Malisense#85]
Work closely with design on this! And consult both the world lore and the writing style guide to see what a normal dungeon note should look like!

**Comment by TheJPerson** [comment]
https://docs.google.com/document/d/1D_yKT3OACueG15dtt6xuRKg8NzBdtJXvbBF9oX8juNI/edit

Doc Link
