### ISSUE TITLE
Writing the church language 

### ISSUE THREAD

**Issue by celine218** [GDACollab/Malisense#91]
the constructed language used by the church people inside dialogue 

Future work to incorporate the language into the game should come up with a few key phrases for the clerics to repeat and define, such as the phrase “asitotheh koila prito staanifi,”  or, in English, “you must fear that which senses powerfully.” 

**Example of Dialogue:** "Asitotheh ko’ila prito sta’anifi, may you fear that which possesses powerful senses, foolish child. Now, fi, go forth." 

**Initial pitch/high priest doc:** https://docs.google.com/document/d/1VhxHGhRkEyHaXD6v-u22F_GC7__3LRhMUpptmAc88Sc/edit?usp=sharing

**Comment by ivydudzik** [comment]
Language Doc: https://docs.google.com/document/d/1AmY_lUjWUKYMVa0idPX0i5SvnJK0CFwd5YUzyYQFx4c/edit?usp=sharing

also I am Ivy Dudzik, naiaelysia on DIscord if you want to contact me about the progress!
