### ISSUE TITLE
(Sprint 2) Add Chromatic Aberration to Screen When Enemy is Chasing Player

### ISSUE THREAD

**Issue by ivydudzik** [GDACollab/Malisense#94]
Duplicate the dungeon scene and make a chromatic aberration effect occur whenever an enemy is in the chasing state.

Use Unity Universal Render Pipeline (we are not using built-in render pipeline)

**Comment by SlimeCubed** [comment]
Zachary - @slime_cubed

**Comment by kevinn-t** [comment]
Kevin - @fardass
